version: '3.8'

services:
  merch-store-service:
      build: .
      container_name: geo-core-service
      env_file:
      - .env
      ports:
        - "8080:8080"
      depends_on:
        db:
            condition: service_healthy
      networks:
        - internal
  
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: geo
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d shop'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

  test-db:
    image: postgres:15
    container_name: test-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_geo
    volumes:
      - ./tests/migrations/:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'test_pg_isready -U postgres -d test-db'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal
networks:
  internal: